Added a notebook on device non_idealities
IBM/aihwkit pull request #437
Opened 2022-10-27 15:11 UTC by GhaziSyed

## Related issues

## Description

## Details

2022-10-28 21:18 UTC, GhaziSyed commented
Phase-change memory devices have found applications in in-memory computing where the physical attributes of these devices are exploited to compute in places without the need to shuttle data between memory and processing units. However, “device nonidealities” in the electrical resistance have a detrimental impact on the achievable computational precision. In this tutorial, we will learn about these non-idealities. We will specifically look into each non-ideality and how they impact computational precision. We will also discuss the software correction schemes to reduce their impact.

2022-11-14 10:03 UTC, kaoutar55 reviewed
Thank you very much @GhaziSyed for your notebook contribution. Very nicely done and a great way to explain all the non-idealities that we use in aihwkit. Please check the comments I added. When you address them, can you add a line to the readme under the notebooks folder that links to your notebook and also adds the link to open it in google co-lab: https://github.com/IBM/aihwkit/blob/master/notebooks/README.md

2022-11-24 16:17 UTC, GhaziSyed commented
Hi @kaoutar55 

Thanks for the nice feedback.
I created a pull request, but realized I did not address all your comments yet.
Please ignore the request as I am working on the newer version

2022-11-24 16:44 UTC, GhaziSyed commented
I have added the updated file now.

2022-12-07 02:24 UTC, kaoutar55 approved these changes

2022-12-09 13:21 UTC, GhaziSyed commented
> 
Thanks and
Done !

2022-12-09 15:52 UTC, maljoras requested changes
Hi @GhaziSyed ,
many thanks for this notebook, sorry I did not have time to look at it earlier. It looks good, however, I have a concern that there is now connection whatsover to the aihwkit usage. The tutorials should best use some aspects of the aihwkit, since this github is the repo for that. I wonder whether one could use some aihwkit code for your experiments? 

For instance, the noise model and drift variations, we have a class in the inference.noise folder that defines that. To properly use it in aihwkit one can just overload that and build your own noise model. Then one can instantiate a aihwkit tile with the new noise model and show the graphs instead of just using custom python matrices. The advantage is obvuisly that one could right away do DNN simulation with the new noise model using aihwkit. That tutorial would be great if one could add that part.

2022-12-09 16:06 UTC, maljoras commented
To be more specific one could show how to add a new class. e.g. 
```python
from aihwkit.inference.noise.pcm import PCMLikeNoiseModel

class MyPCMNoiseModel(PCMLikeNoiseModel):
    def generate_drift_coefficients(self, g_target):
        # define new nu coefficients like you did
    def apply_programming_noise_to_conductance(g_target):
         # define programming noise like you did
```
and then one could use that model with 

```
my_noise  =  MyPCMNoiseModel()
noise_weights = my_noise.apply_noise(weight, t_inference=3600.0)
```
Or use that directly to generate tiles / or modules e.g. 

```python 
from aihwkit.simulator.tiles.analog import AnalogTile 
from aihwkit.simulator.config import InferenceRPUConfig 

rpu_config = InferenceRPUConfig(noise_model=MyPCMNoiseModel())
analog_tile = AnalogTile(50, 50, rpu_config=rpu_config)
analog_tile.set_weights(randn(50,50))
analog_tile.program_weights()   # applied noise model
analog_tile.forward(x)  # forward pass with applied programming noise + other non-idealities
```

2024-08-06 09:42 UTC, Borjagodoy commented
Hi! @GhaziSyed Thank you for all the work done, we are reviewing the open PR and we have noticed that this PR has been unanswered for 2 years, would you be interested in addressing the changes suggested by @maljoras , we could help you with them if needed.

If not, we would proceed to close at least temporarily this PR, being able to reopen it when you need it.

2024-11-22 18:27 UTC, GhaziSyed commented
The PR has been under review for over 3 months. 
Do you foresee a review happening sooner. Could you please follow up on this soon (2e missed some important places to cite the tutorial)

2024-12-09 10:24 UTC, PabloCarmona commented
@GhaziSyed is this PR related to the new one you opened? the #682? Let us know to link them and close this one in preference to the new one. Thanks!

2024-12-20 15:10 UTC, kaoutar55 commented
@GhaziSyed can we close this since you opened a new PR that is doing the same?

2025-01-13 13:50 UTC, closed without merging