Adding the JART v1b memristor model for aihwkit
IBM/aihwkit pull request #501
Opened 2023-05-02 14:27 UTC by ZhenmingYu

## Description

Support a new device type based on JART V1b memristor model and test scripts for that.
Details can be found at https://ieeexplore.ieee.org/document/10052010

## Details
The code was written for the old backend and some adaptations for the new version are needed.
Support for CUDA is strange, where sometimes the results are not transferred back to PyTorch.
Cycle-to-cycle variability is currently not supported for CUDA, as we need fields to save more device-specific parameters.

2023-05-04 13:45 UTC, maljoras commented
@ZhenmingYu, actually I cannot edit your branch anyway, so I will first review it, so that you can make changes

2023-05-04 14:11 UTC, ZhenmingYu commented
@maljoras Thanks a lot for the kind words! I couldn't have done this without your support last year.
So I tried to invite you as a collaborator under my fork, this should enable you to edit the branch.
My plan is to keep the JART_v1b_device branch as is and improve and merge the master branch.

I'm also wondering whether there can be more than 6 device-specific parameters in version 0.7 now with the new backend, which could be helpful with c2c noises.

Thanks a lot for the help!
Zhenming

2023-05-04 14:12 UTC, maljoras requested changes

2023-05-04 14:15 UTC, maljoras commented
We could add some more device-to-device parameters into the kernels. like another par_4 (to have 4 values per synapse). Would this be enough? So you need to modify  them or are they constant?

2023-05-04 14:24 UTC, ZhenmingYu commented
> 
We have implemented a random walk based c2c noise that acts on 4 parameters, starting from their d2d values.
The parameters themselves are already included in the 6 device-to-device parameters, and they each need 2 boundaries to prevent random walks from going too far.

So there are 8 constants in total, that are equal to Par_d2d*(1+-10%), calculated after d2d noises being applied.
Adding 2 par4s would then be enough.

2023-05-04 14:29 UTC, ZhenmingYu commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> + * (C) Copyright 2022 Forschungszentrum Jülich GmbH, Zhenming Yu. All Rights reserved.
Sure, I asked the Forschungszentrum Jülich legal department before about this, and apparently, they have no rules on this end.
This was a suggested line that they mentioned, but I think we can have flexibility on this.

2023-05-04 14:33 UTC, ZhenmingYu commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +          T dNdt = -(c_v0*a_ny0*F_limit*(exp(-(dWa_mean - dWa_difference)/denominator)-exp(-(dWa_mean + dWa_difference)/denominator)))/device_specific_ldisc_cuda;
So dt here is only calculated within a pulse.
If an update is not needed, no voltage is applied, and dNdt during that physical time will be zero, thus ignored in the code.

2023-05-04 14:37 UTC, ZhenmingYu commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +  RPU::math::elemsat<T>(this->context_, weights, this->size_, this->dev_4params_->getData());
Yes, they are, I re-used the getMaxBound() function to get the Max Bound for Oxygen vacancy concentration, Ndisc, which is stored in the hidden persistent weight.

2023-05-04 16:16 UTC, ZhenmingYu commented on JART_v1b_tests/00_basic_test_v1b.py
> +    rpu_config = SingleRPUConfig(device=JARTv1bDevice(w_max=config_dictionary["w_max"],
Did something similar,a yaml_loader.py file that holds the configuration stufff.
I also put stuff like USE_bias in there, so putting it in JARTv1bDevice might not be ideal.

2023-05-04 18:09 UTC, maljoras commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +          T dNdt = -(c_v0*a_ny0*F_limit*(exp(-(dWa_mean - dWa_difference)/denominator)-exp(-(dWa_mean + dWa_difference)/denominator)))/device_specific_ldisc_cuda;
I see. That seems fine then

2023-05-04 18:16 UTC, maljoras commented
OK, I could add 2 par_4 that are both writeable. the current par_2 and par_4 are considered constant. Then you have 8 more writable parameters per synapse, in addition to the 6 constant (par_2, par_4) and the weight and "hidden" weight.

2023-05-05 15:45 UTC, ZhenmingYu commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +    __nanosleep(ns);
Tested, __syncthreads() did work.
However, the performance of the CUDA version seems to be quite slow compared to the GPU version.

2023-05-05 15:47 UTC, ZhenmingYu commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +
True. If I comment out the c2c variations, the torch weight is updated.
I changed these back to constant values and will wait for the 2 extra writable par4s.

2023-05-05 15:49 UTC, ZhenmingYu commented
> 

That would be great. Thanks a lot!
Although I've discovered that the CUDA version runs pretty slow compared to the CPU version some how.

2023-05-05 15:57 UTC, maljoras commented
The GPU kernel currently seems quite complex one could potentially improve the performance. However, for small batch sizes and small weights the CPU version always will be faster, since there is quite an overhead of memory transfer etc in the CUDA kernel. If the compute amount is too small, that part will dominate. If you increase the batch size and weight size GPU should become much faster than CPU.

2023-05-05 16:11 UTC, maljoras commented on src/rpucuda/cuda/rpucuda_JART_v1b_device.cu
> +          Ndisc_double = Ndisc_double + dNdt*base_time_step;
To improve performance, you should put all calculations that are repeated in the loop out side of the loop. In particular if the involve only constant numbers. There are all not necessary and could even be done once on CPU.  

Also note that "pow" and "asin" and "exp" are quite expensive. They could be replaced with the fast __expf etc. or x*x if pow(x, 2).

2023-05-05 18:06 UTC, ZhenmingYu commented
Thanks for the suggestions, it is much faster now.

2023-12-28 20:29 UTC, maljoras commented
moved to #583  since I cannot edit this PR

2023-12-28 20:29 UTC, closed without merging