Updating the AIHWKIT  'Read The Doc' Paper references
IBM/aihwkit pull request #562
Opened 2023-12-11 07:02 UTC by soumyajeet8

## Related issues

## Description

To update the AIHWKIT 'Read the Docs'

## Details

Updated the Paper References section, and also the steps to create a Basic Inferencing experiment using AIHWKIT

2023-12-11 17:42 UTC, maljoras approved these changes

2023-12-11 17:42 UTC, maljoras approved these changes

2023-12-13 20:02 UTC, maljoras approved these changes

2023-12-14 02:40 UTC, kaoutar55 requested changes

2023-12-14 02:40 UTC, kaoutar55 commented on docs/source/using_experiments.rst
> +the ``InferenceCloudRunner`` , in an analogoud way as running experiments locally ::
analogous

2023-12-14 02:40 UTC, kaoutar55 commented on docs/source/using_experiments.rst
> +Similarly the ``BasicInferencing`` Experiment allow setting attributes
allows

2023-12-14 02:40 UTC, kaoutar55 commented on docs/source/using_experiments.rst
> +The ``LocalRunner`` for ``Training`` experimnet and ``InferenceLocalRunner`` for ``Inferencing`` experiment
for  ``Training``  experiment

2023-12-14 02:40 UTC, kaoutar55 commented on docs/source/using_experiments.rst
> +the ``InferenceCloudRunner`` , in an analogoud way as running experiments locally ::
analogoud --> analogous

2023-12-14 02:41 UTC, kaoutar55 commented
Thanks @soumyajeet8 please fix the minor typos

2023-12-18 20:50 UTC, kaoutar55 commented
Hi @soumyajeet8 did you get a chance to make the requested changed. They are minor changes.

2023-12-18 20:50 UTC, kaoutar55 approved these changes

2023-12-19 02:47 UTC, merged

2023-12-19 05:27 UTC, soumyajeet8 commented
HI @kaoutar55 , I have made the minor typo changes as requested since I was facing issue connecting to WSL so I had to resolve that, before I could access the code-base and make changes. The changes are captured in PR #568