Analog Filamentary Conductive-Metal-Oxide (CMO)/HfOx ReRAM device noise model for inference
IBM/aihwkit pull request #702
Opened 2024-12-13 09:26 UTC by soykilian

## Description

A new noise model for inference assessment has been included in the ReRAM noise models, in addition to the statistical noise model from Wang 2022 (Nature).  The presented model is inferred from novel **Analog AFilamentary CMO/HfOx ReRAM** devices.

The noise model accounts for the following effects from experimental characterization:
- **Programming noise**: considered for two different acceptance ranges of the program-and-verify scheme. 
- **Conductance drift**: G-independent conductance relaxation. The drift on the mean and standard deviation of the programmed conductance only depends on the time of inference as a logarithmic function.

2024-12-26 10:01 UTC, PabloCarmona commented on tests/test_inference.py
Check this file for the same as I discussed previously for the code styling changes made by the linter and revert back to original, only left you code and new additions

2025-01-13 13:44 UTC, PabloCarmona commented
Thanks for addressing all the changes requested @soykilian! We need the docs updated with the content you need to put in, if need any help with that let us know is the final thing to final review and merge this PR :)

2025-02-24 11:41 UTC, PabloCarmona requested changes
Except for the commented file, for me the rest is OK. Maybe could be a good a idea to add a notebook that showcase this new device noise model in action, but that is for other time.

2025-02-24 12:45 UTC, soykilian commented on docs/img/.DS_Store
Thanks for the suggestion! For the moment, I included an example to test MVM using this noise model.

2025-02-24 13:55 UTC, jubueche submitted a review, later dismissed

2025-02-24 17:18 UTC, PabloCarmona approved these changes

2025-02-24 18:00 UTC, merged